//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraineeClient.TraineeServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/TrainingService.Models")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseID {
            get {
                return this.CourseIDField;
            }
            set {
                if ((this.CourseIDField.Equals(value) != true)) {
                    this.CourseIDField = value;
                    this.RaisePropertyChanged("CourseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TraineeServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCourses", ReplyAction="http://tempuri.org/IService1/GetCoursesResponse")]
        TraineeClient.TraineeServiceReference.Course[] GetCourses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCourses", ReplyAction="http://tempuri.org/IService1/GetCoursesResponse")]
        System.Threading.Tasks.Task<TraineeClient.TraineeServiceReference.Course[]> GetCoursesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCourseById", ReplyAction="http://tempuri.org/IService1/GetCourseByIdResponse")]
        TraineeClient.TraineeServiceReference.Course GetCourseById(System.Nullable<int> courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCourseById", ReplyAction="http://tempuri.org/IService1/GetCourseByIdResponse")]
        System.Threading.Tasks.Task<TraineeClient.TraineeServiceReference.Course> GetCourseByIdAsync(System.Nullable<int> courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Add", ReplyAction="http://tempuri.org/IService1/AddResponse")]
        int Add(TraineeClient.TraineeServiceReference.Course course);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Add", ReplyAction="http://tempuri.org/IService1/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(TraineeClient.TraineeServiceReference.Course course);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Modify", ReplyAction="http://tempuri.org/IService1/ModifyResponse")]
        int Modify(TraineeClient.TraineeServiceReference.Course course);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Modify", ReplyAction="http://tempuri.org/IService1/ModifyResponse")]
        System.Threading.Tasks.Task<int> ModifyAsync(TraineeClient.TraineeServiceReference.Course course);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Remove", ReplyAction="http://tempuri.org/IService1/RemoveResponse")]
        int Remove(int courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Remove", ReplyAction="http://tempuri.org/IService1/RemoveResponse")]
        System.Threading.Tasks.Task<int> RemoveAsync(int courseId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TraineeClient.TraineeServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TraineeClient.TraineeServiceReference.IService1>, TraineeClient.TraineeServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TraineeClient.TraineeServiceReference.Course[] GetCourses() {
            return base.Channel.GetCourses();
        }
        
        public System.Threading.Tasks.Task<TraineeClient.TraineeServiceReference.Course[]> GetCoursesAsync() {
            return base.Channel.GetCoursesAsync();
        }
        
        public TraineeClient.TraineeServiceReference.Course GetCourseById(System.Nullable<int> courseId) {
            return base.Channel.GetCourseById(courseId);
        }
        
        public System.Threading.Tasks.Task<TraineeClient.TraineeServiceReference.Course> GetCourseByIdAsync(System.Nullable<int> courseId) {
            return base.Channel.GetCourseByIdAsync(courseId);
        }
        
        public int Add(TraineeClient.TraineeServiceReference.Course course) {
            return base.Channel.Add(course);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(TraineeClient.TraineeServiceReference.Course course) {
            return base.Channel.AddAsync(course);
        }
        
        public int Modify(TraineeClient.TraineeServiceReference.Course course) {
            return base.Channel.Modify(course);
        }
        
        public System.Threading.Tasks.Task<int> ModifyAsync(TraineeClient.TraineeServiceReference.Course course) {
            return base.Channel.ModifyAsync(course);
        }
        
        public int Remove(int courseId) {
            return base.Channel.Remove(courseId);
        }
        
        public System.Threading.Tasks.Task<int> RemoveAsync(int courseId) {
            return base.Channel.RemoveAsync(courseId);
        }
    }
}
